# -*- coding: utf-8 -*-
"""
Tools 工具箱
遥感智能解译工具集，覆盖从视觉工具到视觉语言工具的完整链路，按职责分层:

- DataProcessing/  数据处理层（栅格I/O、光谱指数、可视化、GEE、空间分析、数据集制备）
- Model/           模型推理层（推理引擎 + 视觉模型: 分割/变化检测/检测/分类
                             + 视觉语言模型: SamSeg/qwen_sam/qwen_dec）
- PostProcessing/  后处理层（掩码后处理、矢量化、坐标转换）
- KnowledgeRAG/    知识服务层（知识图谱与 RAG）
"""

# ==================== 数据处理层 ====================
from Tools.DataProcessing import (
    # raster_utils
    load_img_by_gdal,
    load_img_by_gdal_geo,
    load_img_by_gdal_info,
    load_img_by_gdal_blocks,
    load_img_bybandlist,
    load_img_normalization,
    load_label,
    load_src,
    get_file,
    find_file,
    geotrans_match,
    polygonize,
    send_message_callback,
    echoRuntime,
    UINT8,
    UINT10,
    UINT16,
    # raster_io
    read_geotiff,
    read_img_with_geo,
    write_img_with_geo,
    get_geo_info,
    copy_geo_to_file,
    # image_ops
    convert_to_8bit,
    calc_spectral_index,
    histogram_match,
    # image_transforms
    ScaleTransform,
    ResizeTransform,
    RandomCropResizeTransform,
    RandomFlipTransform,
    NormalizeTransform,
    RandomExchangeTransform,
    ToTensorTransform,
    ComposedTransforms,
    TransformBuilder,
    # dataset_utils
    split_dataset,
    get_common_files,
    split_image_grid,
    process_synchronized_folders,
    create_folder_structure,
    copy_files_to_splits,
    # band_utils
    detect_band_mapping,
    extract_band_values_at_points,
    geotiff_to_csv,
    # mask_postprocess
    smooth_mask,
    remove_small_objects,
    binary_threshold,
    extract_connected_components,
    polygon_to_coords,
    compute_obb,
    normalize_rotated_rect,
    compute_spatial_location,
    distance_transform_boundary,
    canny_edge,
    sobel_edge,
    batch_extract_boundaries,
    mask_to_polygons,
    raster_to_vector,
    polygon_to_line,
    export_vector,
    pixel_to_geo,
    geo_to_pixel,
    transform_polygon_to_geo,
    transform_polygon_to_pixel,
    transform_line_to_geo,
    wkt_to_epsg,
    # spectral
    calculate_ndwi,
    calculate_ndvi,
    stretch_to_255,
    rgb_to_gray,
    compute_indices,
    # visualization
    save_geotiff_mask,
    visualize_quad_view,
    csv_to_heatmap,
    load_watermask_data,
    # GEE
    resize_tiff_to_500x500,
    convert_to_rgb_255,
    extract_bands_to_csv,
    extract_bands_to_csv_with_mask,
    rgb_255_to_reflectance,
    reflectance_to_rgb_255,
    csv_to_geotiff,
    csv_to_png,
    # spatial
    geojson_to_shapely,
    shapely_to_geojson,
    shapely_list_to_feature_collection,
    validate_features,
    compute_bounds,
    analyze_geometry_types,
    buffer_analysis,
    intersection_analysis,
    erase_analysis,
    shortest_path_analysis,
    export_result,
    export_geojson,
    export_shapefile,
    export_csv,
    export_statistics,
)

# ==================== 后处理层 ====================
from Tools.PostProcessing import (
    smooth_mask,
    remove_small_objects,
    binary_threshold,
    extract_connected_components,
    polygon_to_coords,
    compute_obb,
    normalize_rotated_rect,
    compute_spatial_location,
    distance_transform_boundary,
    canny_edge,
    sobel_edge,
    batch_extract_boundaries,
    mask_to_polygons,
    raster_to_vector,
    polygon_to_line,
    export_vector,
    pixel_to_geo,
    geo_to_pixel,
    transform_polygon_to_geo,
    transform_polygon_to_pixel,
    transform_line_to_geo,
    wkt_to_epsg,
)

# ==================== 模型层 ====================
from Tools.Model import (
    # inference
    load_model_cached,
    clear_model_cache,
    estimate_memory_usage,
    adjust_batch_size,
    pad_image_to_multiple,
    create_sliding_windows,
    create_weight_map,
    stitch_result,
    tif_cropping_array,
    stitch_tif_result,
    predict_img_with_smooth_windowing,
    cheap_tiling_prediction,
    # SamSeg
    load_model,
    load_classes,
    build_palette,
    run_inference,
    inference_single_view,
    slide_inference,
    multipass_inference,
    aggregate_logits,
    postprocess,
    extract_edge,
    extract_fpn_features,
    compute_fpn_similarity,
    compute_instance_change_map,
    PAMR,
    LocalAffinity,
    LocalAffinityCopy,
    LocalStDev,
    LocalAffinityAbs,
    DEFAULT_CLASSES,
    NAME_COLOR,
    HAS_RASTERIO,
)
